### ISSUE TITLE
LSP broken on NVim(AstroNvim) with exit code 1 after latest update

### ISSUE THREAD

**Issue by ASoldo** [tailwindlabs/tailwindcss-intellisense#1004]
Hi, today I updated my config and now when i open my project that use tailwindcss i get this errors:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/1175537/789cad76-d8b9-4a81-943c-571fa1661c77)

This is log from lsp.log:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/1175537/d1a6ce77-dd78-4840-bfbf-d5b206e60ba4)

Setup:
`installed version 0.0.18`
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/1175537/fc37418f-7047-41a2-b75d-a62d0929f384)

Does anybody know why or how can I fix this?

Thank you!

**Comment by thecrypticace** [comment]
Hi! What version of Node are you using?

**Comment by ASoldo** [comment]
I am using NVM with `Node.js v18.12.1`. But default version is lower. After switching and setting nvm default shell to this version lsp is working again.

**Comment by thecrypticace** [comment]
Okay — I bumped the minimum node version for the language server to Node v18 a while back because of some newer APIs we use.

This is technically addressed in the insiders build of the language server _anyway_ because of some older versions of VSCode but I'd suggest using at least Node v18 when possible. 👍
