### ISSUE TITLE
If hide tailwind.config.js in VSCode explorer, intellisense plugin not work.

### ISSUE THREAD

**Issue by nyssance** [tailwindlabs/tailwindcss-intellisense#1052]
**What version of VS Code are you using?**

v1.93.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.12.10

**What version of Tailwind CSS are you using?**

v3.4.11

**What package manager are you using?**

bun

**What operating system are you using?**

macOS, Windows

**Tailwind config**

```js
// Paste the contents of your Tailwind config file here
```

**VS Code settings**

```json
    "files.exclude": {
        ...
        "tailwind.config.js": true
    },
    "search.exclude": {
        ...
        "tailwind.config.js": false
    },
```

**Describe your issue**

If hide tailwind.config.js in VSCode explorer, intellisense plugin not work.

**Comment by isimmons** [comment]
Same if I try to use the settings.json `"tailwind.files.exclude": ["tailwind.config.js"]`
Now no files get intellisense. 

Reason I'm trying to do this is because VSCode built in `editor.colorDecorators` does not work for tailwind.config.js when the tailwind extension is enabled and when I just use the tailwind extension, I get no colors in the config file.
