### ISSUE TITLE
Pug class="" completion

### ISSUE THREAD

**Issue by smhmd** [tailwindlabs/tailwindcss-intellisense#125]
Thanks for the update.

I think this used to work (with problems.)

![image](https://user-images.githubusercontent.com/46059092/84416622-5bec0180-ac0c-11ea-94b9-ed1a813c5ccc.png)
![image](https://user-images.githubusercontent.com/46059092/84415823-3f02fe80-ac0b-11ea-98c8-da93a598f8d7.png)

If you want to write classes like `w-1/2` in pug (vue with `lang="pug"`), you have to put them in the class attribute or change their name. Before [0.3.0](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0), I recall it working, but you also had completion inside other unrelated attributes.

**Comment by bradlc** [comment]
Ah damn, sorry about that @smhmd! I know exactly what the issue is!

**Comment by smhmd** [comment]
@bradlc I just remembered. The issue was `.` activating the completion:

![image](https://user-images.githubusercontent.com/46059092/84419217-33fe9d00-ac10-11ea-92ce-9ccbbfa6655b.png)

Having completion if there is no text is debatable (not necessary in my opinion,) but after some text, it definitely shouldn't trigger completion:

![image](https://user-images.githubusercontent.com/46059092/84418957-d0746f80-ac0f-11ea-9ec3-f8eb2ee1ad31.png)

**Comment by smhmd** [comment]
Ideally, this should trigger completion:

![image](https://user-images.githubusercontent.com/46059092/84419537-a7081380-ac10-11ea-8185-8547661334a7.png)

(If you're not familiar with Pug, this is how you put multiple elements on the same line: [tag interpolation](https://pugjs.org/language/interpolation.html#tag-interpolation))

**Comment by bradlc** [comment]
One last update on this: the extension doesn't currently aim to support pug syntax. However it _happens_ to support a lot of use-cases because of the **Emmet** support. The example above (`p.text-white #[span.tex]`) doesn't show completions because it is not a valid Emmet string.

Side note: The extension has [a new experimental setting](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) which allows defining custom regular expressions to match against for completions. This may allow improved pug support although I am not sure how simple it would be to express some of the use-cases as regular expressions.
