### ISSUE TITLE
[Feature request] Warn if translate is present but there is no transform

### ISSUE THREAD

**Issue by estevanmaito** [tailwindlabs/tailwindcss-intellisense#148]
This issue was raised in Tailwind's Discord, but it's something that is frequently asked (I also remember this https://github.com/tailwindcss/tailwindcss/discussions/1808): why isn't `translate` working?.

### Solution

Show a warning (yellow underline) if `translate` is used without `transform`.

---

[Original comment](https://discord.com/channels/486935104384532500/486935104384532502/731891075207266415):

> It's important to note that you have to include the transform utility before you can use any of Tailwind's built-in transforms. Otherwise, -translate-x-1/2 will silently not work.

**Comment by bradlc** [comment]
Thank for the suggestion @estevanmaito! I think this is a cool idea, but would be prohibitively difficult to implement. In this example the extension sees **three** separate class lists. This helps to ensure that you don't get a conflict warning ("`translate-2` and `translate-4` apply the same property") when using conditional classes:

```html
<div class="transform {{ $condition ? 'translate-2' : 'translate-4' }}"></div>
```

But the problem with your suggestion is that you would get a warning for each of the `translate-*` classes because `transform` is missing in their respective class lists.
