### ISSUE TITLE
Support tailwindcss 1.7.0

### ISSUE THREAD

**Issue by brielov** [tailwindlabs/tailwindcss-intellisense#173]
<img width="621" alt="Screen Shot 2020-08-20 at 09 06 45" src="https://user-images.githubusercontent.com/42145089/90768017-7c979e00-e2c4-11ea-8a43-4bdbbf8be130.png">

Also, intellisense for gradients and other features are not showing up.

**Comment by bradlc** [comment]
`v0.4.2` of the extension includes some changes which improve compatibility with Tailwind v1.7:

* Disable `invalidApply` lint rule when `applyComplexClasses` experimental flag is enabled.
* Show all classes in `@apply` completion list when `applyComplexClasses` experimental flag is enabled.
* Update color parsing so that color swatches are shown for the new gradient classes.

Does this fix the issues you were having?

> Also, intellisense for gradients and other features are not showing up.

Could you elaborate on this please? What specifically isn't working?

**Comment by bradlc** [comment]
I think this is resolved but please open a new issue if not 👍
