### ISSUE TITLE
Add intellisense when using classnames plugin

### ISSUE THREAD

**Issue by davea38** [tailwindlabs/tailwindcss-intellisense#197]
I write a lot of react code and use the https://github.com/JedWatson/classnames plugin for conditional CSS rendering.

Any chance you could enable this plugin to detect the classNames function?

```javascript
import classNames from 'classnames';

<div className={classNames([
   'flex flex-col',
   ...
])} />
```

**Comment by 0az** [comment]
I have my own minimalist version of this (`const kn = (...classes) => classes.filter(e => !!e).flat().map(e => e + '').join(' ')`), which works in enough cases for a copy/paste snippet in every project.

No idea what the low level parsing looks like, but detecting the `class={}`/`class=""` for Preact JSX or `className={}` for React JSX would probably suffice to support my use case as well: just enable the relevant completions inside every string in all such contexts.

**Comment by bradlc** [comment]
Hey @davea38! Any strings inside the class(Name) attribute should already trigger the completions:

![image](https://user-images.githubusercontent.com/2615508/95441948-af6c2300-0952-11eb-8f90-94aed1c305fc.png)

Is this not working for you?

**Comment by kristiandupont** [comment]
@bradlc that's great if you call `classNames` inline. However, I frequently call it before the return statement. I too would love either a sophisticated detection of the classnames package or maybe something similar to what [Headwind does](https://github.com/heybourn/headwind#headwindclassregex).

**Comment by davea38** [comment]
Thanks for your reply @bradlc! As @kristiandupont points out, the majority of the time I am using classNames before a JSX return in a plain javascript function. It's less of a problem as I become more familiar with Tailwind, but my brain has a finite limit for the amount of 'stuff' it can hold... :)

**Comment by eddyw** [comment]
<img width="251" alt="Screen Shot 2020-11-19 at 20 42 14" src="https://user-images.githubusercontent.com/1407526/99667679-b6389a80-2aa7-11eb-8e95-b3ec13d3a31b.png">
You sort of can 😝. However, as soon as you format JS adding spaces between `=` char, it'll stop intellisense and the color decorations will disappear.

This "works" because of this:
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/b3fef941b6515870d8bd039a75748d91a5564b69/src/lsp/providers/completionProvider.ts#L133

It'd be great if the RegExp allowed matching `className( )` with parens. Then you could always do:
```javascript
import { clsx as className } from './my-classNames-lib'

const styles = className({ white: 'text-white' }, 'bg-green-400')
```

**Comment by eddyw** [comment]
Since it's just a regular expression, you can use JS comments to make it match `class={ }` like this:
<img width="269" alt="Screen Shot 2020-11-19 at 20 50 03" src="https://user-images.githubusercontent.com/1407526/99668517-cdc45300-2aa8-11eb-9823-27b7529e25e4.png">
Anyways, it'd great if there was a better and official solution.

**Comment by bradlc** [comment]
Please see #129, in particular my [recent comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659)

**Comment by davea38** [comment]
@bradlc - thank you! Will try this feature out in the latest version :)
