### ISSUE TITLE
css intellisense is broken in layers block

### ISSUE THREAD

**Issue by germsb** [tailwindlabs/tailwindcss-intellisense#253]
Intellisense for css properties and values doesn't work in layers block of css file. Selectors are ok 

in layer
![Imgur](https://i.imgur.com/UyY49nS.jpg)

out
![Imgur](https://i.imgur.com/B04YOJY.jpg)

tailwindcss 2.0.2
tailwindcss-intellisense 0.5.7

**Comment by brc-dd** [comment]
Also, while using SCSS, the `@layer` directive is not highlighted. Nor the layer utilities like the ones defined in the [docs](https://tailwindcss.com/docs/functions-and-directives#layer) show up on the intellisense.

### Extension and Editor Details

```txt
Name: Tailwind CSS IntelliSense
Id: bradlc.vscode-tailwindcss
Description: Intelligent Tailwind CSS tooling for VS Code
Version: 0.6.6
Publisher: Brad Cornes
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss
```

```txt
Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21343
```

**Comment by bradlc** [comment]
Since `v0.8.0` the extension now provides a "Tailwind CSS" language mode, that maintains CSS IntelliSense even when using Tailwind-specific at-rules. You can use this by clicking on the "Select Language Mode" button in the corner of the VS Code window and selecting "Tailwind CSS":

<img width="184" alt="Screenshot 2022-04-19 at 20 54 01" src="https://user-images.githubusercontent.com/2615508/164084946-d8dc651b-7a9d-4bcc-8032-8bb531c5bb72.png">

You can also set this as the default mode for all `.css` files using the `files.associations` setting:

```
"files.associations": {
  ".css": "tailwindcss"
}
```
