### ISSUE TITLE
Feature request: when a class is selected with the mouse/has the cursor on it, highlight its variants

### ISSUE THREAD

**Issue by y1n0** [tailwindlabs/tailwindcss-intellisense#254]
It would nice if we could easily identify the different variants of a class that are used on the same element. Just like in VSCode, when we select a word, all of it occurrences in the document are highlighted.

**Comment by bradlc** [comment]
Hey @y1n0, thanks for the suggestion! This is definitely an interesting idea, and one I have thought about in the past and even implemented in prototypes. I am going to close this though because I think a feature like this is kind of outside the scope of the project ultimately. I could see this feature being a cool little standalone extension one day though! Thanks!
