### ISSUE TITLE
Validate @apply rules?

### ISSUE THREAD

**Issue by pikeas** [tailwindlabs/tailwindcss-intellisense#285]
Is there any way to have this extension flag for:

```
<style>
    p {
        @apply not-real;
    }
</style>
```

This would be great for catching typos.

**Comment by bradlc** [comment]
Hey @pikeas. Thanks for the suggestion! Agree this would be nice, but it's not possible currently, because the extension isn't actually aware of any of your custom CSS, only CSS generated by Tailwind CSS itself. In the example below the extension doesn't know that `.one` exists, so would show an error, which is obviously incorrect:

```css
.one {
  color: red;
}

.two {
  @apply one;
}
```

This is kind of related to #227 in that the core issue is that the extension isn't aware of custom CSS at all. This is a non-trivial issue to solve and there's no immediate plans to implement it.
