### ISSUE TITLE
Show `px` values besides `classNames` while mouse hover

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss-intellisense#310]
I can see the values besides `classNames` when I hover via pressing up & down keys like `h-0 /* 0px */`.

I want to be able to see the values when I hover over them via mouse as well. Because I can't go down quite fast via keys but I can via scroll.

PS: This is easily the best feature of this extension. I use it so much :)

**Comment by bradlc** [comment]
If I'm understanding correctly I don't think this is possible. The additional info on the right side (the "detail") is only shown when an item is focused. That's just how VS Code works. There are some new label types coming soon I think, for example:

![image](https://user-images.githubusercontent.com/2615508/116306019-71bed280-a79c-11eb-8d94-014e3ad20c6f.png)

It looks like these types of label are always visible, but this would require every completion item to be resolved upfront, which I don't really want to do because there can be _a lot_ of items.
