### ISSUE TITLE
[Feature Request]: Color decorators for defining color with CSS variables

### ISSUE THREAD

**Issue by lianghx-319** [tailwindlabs/tailwindcss-intellisense#409]
## Scenario

- Following the official docs to define my custom theme, using CSS variables
- The editor color decorators can't read the real CSS variable value in runtime
![image](https://user-images.githubusercontent.com/27187946/133932887-1ae87bbb-023b-42af-9e68-bbfd3f2849fb.png)

## Requirement

- Is there some way can write a real value with comment, make color decorators works?
- When with comment like that, color decorators show `rgb(255, 236, 232)` but not `red`
![image](https://user-images.githubusercontent.com/27187946/133933004-42890887-a480-43f3-8441-508425cad7db.png)

**Comment by bradlc** [comment]
Hey @lianghx-319. Thanks for the suggestion! It's a neat idea but I don't think we're going to add this. It would be very complex to implement and I don't think the use-case is strong enough.

**Comment by dBianchii** [comment]
@bradlc Maybe we found a use case here. Would love it if we could have this fixed

https://github.com/shadcn/ui/issues/199

**Comment by micobarac** [comment]
Any update on this, 2 years later?

**Comment by ruymon** [comment]
> Hey @lianghx-319. Thanks for the suggestion! It's a neat idea but I don't think we're going to add this. It would be very complex to implement and I don't think the use-case is strong enough.

Hi, @bradlc! 👋🏼

Thanks for your input from two years ago. I've noticed the continued growth of tools such as [shadcn](https://github.com/shadcn-ui/ui) and how they are inclined to standardize CSS variables for storing themes. It seems like addressing this issue could significantly benefit developers now. Considering the advancements in technology and the evolving needs of the community, could the team possibly reconsider implementing this feature? Your insights would be greatly appreciated!

Regards,

**Comment by Sliov** [comment]
Came across the same issue as our team is moving to css variables to define our global tokens.

Colors & spacing are now just seen as "variable", what I love about this plugin tho is the ability to lookup the exact spacing unit or colour when hovering a class.

as @ruymon mentioned, I hope the Tailwind team picks it up given how popular CSS variables are now for declaring global tokens/themes.

**Comment by kejlerj** [comment]
You can use the vscode extension [colorInfo](https://marketplace.visualstudio.com/items?itemName=bierner.color-info) and just write in comment the hsl color in comment:
![image](https://github.com/shadcn-ui/ui/assets/24431487/081073e5-b0b4-42c3-a4f5-05f17e623ac4)

**Comment by pivotpointux** [comment]
+1

**Comment by matowang** [comment]
> You can use the vscode extension [colorInfo](https://marketplace.visualstudio.com/items?itemName=bierner.color-info) and just write in comment the hsl color in comment: ![image](https://private-user-images.githubusercontent.com/24431487/298426254-081073e5-b0b4-42c3-a4f5-05f17e623ac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzAxMTcsIm5iZiI6MTcwOTk2OTgxNywicGF0aCI6Ii8yNDQzMTQ4Ny8yOTg0MjYyNTQtMDgxMDczZTUtYjBiNC00MmMzLWE0ZjUtMDVmMTdlNjIzYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA3MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NzQ4YzA0NmI4MmZiMTliMmNjZDNjNjFkOWQ2NjVjNmUwZjUxMTFiYzc4YWFlMDBlZWUxN2M1Y2ZlYmRiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yrVlBa7HMf-4nCW-xR1pXviOK5HIhN6liWwHz7UOZg)

How did you get the color to highlight? Mine only shows on hover

<img width="570" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/38610107/8595176d-f3fd-4dd9-b49a-f3edae849a5b">

**Comment by LucasMatuszewski** [comment]
Hey, I have created a Pull Request to **Color Highlight** VSCode extension to include `WSL without function` option and floats support:
https://github.com/enyancc/vscode-ext-color-highlight/pull/200

It already supports `RGB without function` (disabled by default) so if you are using RGB like `--primary: 200 200 200;` it will work for you right now.

Here is how it looks for me:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/28517564/2a08eb94-823d-4c8c-a65f-a5c80a7fc6bd)

Hopefully, @enyancc will accept my PR soon and publish a new version of the extension.

If not, here is a link to download the packaged VSIX file (the extension as a file):
https://we.tl/t-VHTnVChsMR

To install it you can just go to "Extension", click the three dots menu icon (up-right corner of extensions), and select Install from VSIX... or with CLI: `code --install-extension myextension.vsix`

After installation, you have to enable `hslWithoutFunction` / `rgbWithoutFunction` options in settings. You can also set a list of languages / files this setting will work for (or exclude languages). And I prefer the "dot after" option instead of the full background color.

I may also create a forked new Extension dedicated to Tailwind (with only the minimum options we need) for better performance (the current plugin runs on every VSCode window and parses every text for any type of color definition, but I didn't notice any issues, all works fine with it enabled).

Please let me know if you would like that dedicated extension, and what are the most important/minimal features?

I've also tried to add this feature to the **Color Info** plugin, my RegEx worked fine but I couldn't debug it. But a minimalistic square with color is enough for me. If somebody would like to help with Color Info I can create a WIP PR (I was probably very close to make it work, but didn't have time to solve it).

BTW. It doesn't support highlighting custom class names in your code, sorry... It would be much more complicated ;)
But it will add color anywhere you have `000.00 000% 000%` or `000, 000.00%, 000%` in your code, including floats (or you can change extension settings to make it work only in CSS files, which will be better for performance).

So... No more unnecessary comments in your CSS files :D
