### ISSUE TITLE
Intellisense doesn´t work with [ or ] letters in project path

### ISSUE THREAD

**Issue by dunak-debug** [tailwindlabs/tailwindcss-intellisense#429]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**

v2.2.17

**What package manager are you using?**

yarn

**What operating system are you using?**

Windows 11

**Reproduction URL**

- Put project inside folder with `[` or `]` in path

**Describe your issue**

Intellisense doesn´t work if just any folder inside full path contains `[` or `]`. No errors/warnings.

**Comment by bradlc** [comment]
Thanks for reporting! This will be fixed in the next release, via 8766f6d7ded6ab1eecf4f15e5d35ce7be10ab0f8. For reference, the solution is the same as the one found in `vscode-eslint`: https://github.com/microsoft/vscode-eslint/blob/01c81e9f0b9f86978e9cd47b90176fd2ab5cc28e/server/src/eslintServer.ts#L1224
