### ISSUE TITLE
Highlight with @screen modifier gone for Vue SFC files

### ISSUE THREAD

**Issue by hymair** [tailwindlabs/tailwindcss-intellisense#436]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.2

**What version of Tailwind CSS are you using?**

For example: v2.1.16

**What package manager are you using?**

yarn

**What operating system are you using?**

Windows

**Describe your issue**

v0.7.2 introduced a code highlighting bug in Vue SFC files. After a `@screen` keyword is used everything below loses proper highlighting.

v0.7.1
![image](https://user-images.githubusercontent.com/21025134/140889231-abcc8d5e-887b-4af5-81d7-8334b84115d0.png)
v0.7.2
![image](https://user-images.githubusercontent.com/21025134/140889293-3702b691-5698-44c7-9474-812552bc1c6a.png)

**Comment by bradlc** [comment]
Hey @hymair. I haven't been able to reproduce this issue with the latest version of the extension, despite trying different Vue setups with [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) and [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar). Since this is an old issue I'm thinking that maybe it worked itself out. If you're still seeing this please open a new issue and include a list of VS Code extensions you have installed along with your VS Code settings in JSON format

**Comment by hymair** [comment]
This is still an issue. Sure, I will open a new issue.
