### ISSUE TITLE
Laravel @if statement in blade for active links

### ISSUE THREAD

**Issue by ThisIsPuzzle** [tailwindlabs/tailwindcss-intellisense#452]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.4

**What version of Tailwind CSS are you using?**

For example: v3.0.7

**What package manager are you using?**

For example: npm

**What operating system are you using?**

For example: Windows

**Reproduction**
```
<a href="#" class="@if(request()->routeIs($page['routeName'])) text-blue-400 border-blue-400 hover:border-blue-400 @else text-gray-500 border-gray-900 hover:border-pink-400 @endif">url</a>
```

**Describe your issue**

When trying to have differente color of the text for the active / unactive URL in Blade template, i get the warnings in the console and it induces into the error that you are having a problem.

**Comment by bradlc** [comment]
Hey @ThisIsPuzzle. This is an unfortunate limitation of the class parser. There is a workaround, which is to use Blade's `{{ }}` echo statements and a ternary operator instead of `@if` and `@else`:

```
<a href="#" class="{{ request()->routeIs($page['routeName']) ? 'text-blue-400 border-blue-400 hover:border-blue-400' : 'text-gray-500 border-gray-900 hover:border-pink-400' }}">url</a>
```

I am going to close this as the limitation is not something that we are likely to address in the foreseeable future.
