### ISSUE TITLE
IntelliSense not working with unstyled elements. (without class)

### ISSUE THREAD

**Issue by dionweb** [tailwindlabs/tailwindcss-intellisense#458]
**What version of Tailwind CSS IntelliSense are you using?**

 v0.7.5

**What version of Tailwind CSS are you using?**

v3.0.12

**What package manager are you using?**

npm

**What operating system are you using?**

Fedora 35 - Linux

**Reproduction**

I am working on a project built with Node.js, Express and EJS templating. 

I installed the Tailwind CSS IntelliSense extension (Visual Studio Code - Version: 1.63.2)  and Tailwind CSS with the Tailwind CLI tool  (followed the official docs).

Also i have already created a valid `tailwind.config.js` file.

``` 
module.exports = {
    content: ["./views/**/*.{html,ejs}"],
    theme: { extend: {} },
    plugins: [],
};
``` 

**Describe your issue**

The problem is that IntelliSense doesn't seem to work with unstyled elements.
If i try to add a tailwind class to a styled element (has already a class) then the IntelliSense works as expected.

![1](https://user-images.githubusercontent.com/40441225/148602138-b098bc2d-82ed-4179-98a4-6427a824ff01.png)

But when i try to add a class to an unstyled element (has not a class) then it doesn't work.

![2](https://user-images.githubusercontent.com/40441225/148602156-455ec8de-08cd-4977-884e-805f447f45ee.png)

**Comment by rico0808** [comment]
me to, it worked before, v0.7.5 doesn't work

**Comment by NovusOpus** [comment]
As a temporary fix, when there's no class before use an `empty space(spacebar key)` and then start writing and the suggestions are going to show up.

**Comment by bradlc** [comment]
Hey @dionweb. This is likely because you are using some kind of attribute autocomplete, for example selecting this:

<img width="692" alt="" src="https://user-images.githubusercontent.com/2615508/149522591-ee22de1c-dc36-4c48-84fe-db761ddf4e61.png">

Unfortunately this is just how VS Code triggers completions and we can't do anything about it. Tailwind CSS IntelliSense registers "trigger characters" that will trigger completions, and these include `"` and  ` ` (space). So if you aren't typing these characters manually then the completions won't trigger. You can trigger completions manually using the `Trigger Suggest` command (`Ctrl+Space` by default)
