### ISSUE TITLE
[Request] Make extension work with default config found in node_modules

### ISSUE THREAD

**Issue by johnRivs** [tailwindlabs/tailwindcss-intellisense#52]
I see that this extension is looking for a file with one of these names `**/{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js` but the name of the [config files](https://github.com/tailwindcss/tailwindcss/tree/master/stubs) in node_modules are a bit different.

Could you include those names for projects where there's no config file outside node_modules?

**Comment by alivefromupstairs** [comment]
Yeah, fix these 14 issues once and for all by just allowing`tailwind.js` as valid config file name.

**Comment by mbulfair** [comment]
I have my config in a custom component in my `node_modules` how can I tell this extension to look in a particular destination for the config so the `@apply` picks up on the styles I have?

Path would be `node_modules/@component/src/tailwind.config.js`

**Comment by bradlc** [comment]
We try to be as responsible as possible with regards to extension activation, which is why we use that specific activation event. The problem is that by default VS Code excludes `node_modules` folders from searches, which makes sense, but means that a `tailwind.config.js` in there won't trigger the activation event. In the future we may change the activation event, perhaps to [`onStartupFinished`](https://code.visualstudio.com/api/references/activation-events#onStartupFinished), but for now this is a limitation.

For now if you want to use the extension with the default config you could create an "empty" config file:

```js
// tailwind.config.js
module.exports = {}
```

And if you want to use a config that exists under `node_modules` you could create your own config file and re-export it:

```js
// tailwind.config.js
module.exports = require('@component/src/tailwind.config.js')
```
