### ISSUE TITLE
Tailwindcss Intellisense throws error with import statement inside the config

### ISSUE THREAD

**Issue by UliPrantz** [tailwindlabs/tailwindcss-intellisense#565]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6

**What version of Tailwind CSS are you using?**

"@nuxtjs/tailwindcss": "^4.2.1" and "@tailwindcss/forms": "^0.5.2"

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Describe your issue**

When using an import inside the `tailwind.config.js` e.g. when using `tailwindcss/forms` the tailwind intellisense plugin throws the following error:
```
import forms from '@tailwindcss/forms';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1085:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at Module.Vd._require.Gi.default.require (/Users/uli/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:179:63908)
    at require (node:internal/modules/cjs/helpers:102:18)
```

with the following content of the `tailwind.config.js` file:

```
import forms from '@tailwindcss/forms';

export default {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    forms
  ],
}
```

The project compiles successfully and is completely working therefore the plugin should also work and don't throw an error.

**Comment by tbusillo** [comment]
Ran into the same issue as have been using Vite and try to do everything via ESM. I do not think imports will work due to how they're requiring other node packages in their package, sadly. 

However, I ended up changing the file extension to `.cjs` and going back to using `require()` and `module.exports` and it started working instantly. 

Example below: 

```js

// tailwind.config.cjs

module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx, md, mdx}'],
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')]
};

**Comment by bradlc** [comment]
Hey @UliPrantz. The extension doesn't support ESM config files because Tailwind itself does not support ESM config files **natively**. We continue to explore support for ESM config files in Tailwind and when/if we add that we will also update the VS Code extension. As @tbusillo said you should be able to use a `tailwind.config.cjs` file with CommonJS instead.
