### ISSUE TITLE
wrong postcss version detected when there are more present

### ISSUE THREAD

**Issue by johkade** [tailwindlabs/tailwindcss-intellisense#575]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6

**What version of Tailwind CSS are you using?**

v2.2.19

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/johkade/SpacexGraphQL

**Describe your issue**
Beforehand: I've worked around this issue to get it working, but hoping to find a more elegant way. See the repro and solution at the bottom. 🙃

In a React Native project using tailwind I have two separate versions of postcss installed through peer dependencies:
- postcss@8.4.14 through [react-native-tailwind.macro](https://github.com/finkef/react-native-tailwind.macro)
- postcss@7.0.39 through @expo/webpack-config (necessary for [moti](https://github.com/nandorojo/moti) web support)

When I open my project in VS Code, Tailwind CSS Intellisense doesn't work and shows this error:

<img width="456" alt="Screenshot 2022-07-09 at 14 17 27" src="https://user-images.githubusercontent.com/48554608/178105428-ba031937-c4cd-42ce-9192-5567728001c9.png">

The logs indicate, that the wrong version of postcss is picked up (7.x.x), which is why the extension fails:

`Found Tailwind CSS config file: /Users/johanneskade/Desktop/tessst/tailwind.config.js
Loaded postcss v7.0.39: /Users/johanneskade/Desktop/tessst/node_modules/postcss
Loaded tailwindcss v2.2.19: /Users/johanneskade/Desktop/tessst/node_modules/tailwindcss
[Error - 2:11:23 PM] Tailwind CSS: PostCSS plugin postcss-nested requires PostCSS 8.`

**Reproduction**
- clone the example repo
- yarn install
- open project in VS Code
- **Extension shows error and doesn't work/autocomplete**

**Workaround:**
- yarn add postcss // in root dir
- extension starts working as expected

**Ideal solution/expected behavior**
It would be cool if the extension finds the latest installed version by itself, or alternatively, I can configure the used version through the Extension-config in settings.json

Would be great to find a more elegant fix for this instead of installing a third version in the project 🙂
Thanks for any help

**Comment by bradlc** [comment]
Hey @johkade. I think this is related to your dependencies and how your package manager is handling them. When I run `yarn` in your repo I get the following warning:

```
"react-native-tailwind.macro > twrnc > tailwindcss@2.2.19" has unmet peer dependency "postcss@^8.0.9".
```

So it seems that `yarn add postcss` is the solution, as you have already discovered.

Alternatively I have found that using [`resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) also fixes your issue:

```
"resolutions": {
  "postcss": "^8.4.14"
}
```

_I am not too familiar with Yarn and especially not `resolutions` so this may or may not be a good idea._

Lastly, you could use npm (>= `v7.0.0`) instead of Yarn since [it automatically installs peer dependencies](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/), and I have verified that it fixes the issue in your repo.

I hope that helps!
