### ISSUE TITLE
cssConflict in JS conditional with experimental classRegex

### ISSUE THREAD

**Issue by zkulbeda** [tailwindlabs/tailwindcss-intellisense#582]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6

**What version of Tailwind CSS are you using?**

v3.1.6

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

[**Reproduction URL**](https://gist.github.com/zkulbeda/eeefa0b12f25ff4ee2ddf846f2b81332)

**Describe your issue**

When using custom classRegex in JS code, plugin marks classes as conflict in `if` conditionals.

![image](https://user-images.githubusercontent.com/24959171/180752964-dff08695-b22c-40bd-941e-5fa4c080cb84.png)

I can turn off conflicts warnings, but I think it isn't the solution.

**Comment by bradlc** [comment]
Hey @zkulbeda. This is because your regular expressions are not quite matching the correct ranges. If we take a look at your third pattern (the one for matching double quotes) you can see that it's matching too much: https://regex101.com/r/9MJI6F/1

Here it is tweaked slightly: https://regex101.com/r/HkdM41/1

```diff
- \/\*\s*tw\s*\*\/\s*"([^']*)"
+ \/\*\s*tw\s*\*\/\s*"([^"]*)"
```

And here's the changes you can make to your settings that should resolve your issue:

```diff
{
  "settings": {
    "tailwindCSS.experimental.classRegex": [
-     "/\\*\\s*tw\\s*\\*/\\s*`([^']*)`",
+     "/\\*\\s*tw\\s*\\*/\\s*`([^`]*)`",
      "/\\*\\s*tw\\s*\\*/\\s*'([^']*)'",
-     "/\\*\\s*tw\\s*\\*/\\s*\"([^']*)\"",
+     "/\\*\\s*tw\\s*\\*/\\s*\"([^\"]*)\""
    ],
  }
}
```

I hope that helps!
