### ISSUE TITLE
cssConflict warning on different classes

### ISSUE THREAD

**Issue by jiradedm** [tailwindlabs/tailwindcss-intellisense#598]
**What version of Tailwind CSS IntelliSense are you using?**
0.8.6

**What version of Tailwind CSS are you using?**
3.1.8

**What package manager are you using?**
npm

**What operating system are you using?**
macOS

**Describe your issue**:
I got a cssConflict warning from 2 different elements.

<img width="1136" alt="Screenshot at Aug 30 15-04-44" src="https://user-images.githubusercontent.com/90127132/187384544-c32bd33e-8765-407e-af86-dfc1563ebece.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/90127132/187386630-ce26cbe0-042c-4741-b76f-bef6ef7389b3.png">

**Comment by bradlc** [comment]
Are you using the `tailwindCSS.experimental.classRegex` setting?

**Comment by jiradedm** [comment]
yes

<img width="376" alt="image" src="https://user-images.githubusercontent.com/90127132/187591119-478015cf-c288-4864-ac0c-d800e6b4177f.png">

**Comment by bradlc** [comment]
Thanks for sharing. This is happening because your regular expression is too broad. It should only match lists of classes, but yours matches _everything_ after a `` ` `` that isn't a `` ` ``. Check out this example that shows what your expression is matching: https://regex101.com/r/sh0qbc/1

I think adding a `` ` `` to the end of your expression should be what you want (example [here](https://regex101.com/r/7sXcGz/1)):

```
"tailwindCSS.experimental.classRegex": [
  "`([^`]*)`"
]
```

I hope that helps!
