### ISSUE TITLE
Set path for tailwindcss config and binaries per-project?

### ISSUE THREAD

**Issue by milogert** [tailwindlabs/tailwindcss-intellisense#601]
This is more of a question.

Is it possible to set the path of where the tailwindcss install and config lives? For instance, in Elixir + Phoenix projects all the javascript lives in `./assets`, including the `tailwind.config.js` file and the `package.json`.

Currently my solution is to install tailwindcss in the project root and symlink the config from `./assets/tailwind.config.js` to `./tailwind.config.js`. These steps allow the LSP to pick up the proper data, but it's pretty clunky.

I am not sure about the opinions of the Elixir Tailwind module maintainers, but if this doesn't seem like an issue here I can definitely ask over there to see if anybody has had any luck with this.

**Comment by bradlc** [comment]
Hey @milogert. You can configure the location of your config file(s) using the [`tailwindCSS.experimental.configFile` setting](https://github.com/tailwindlabs/tailwindcss-intellisense#tailwindcssexperimentalconfigfile). It's worth noting that you shouldn't have to do this if you only have one config file in your project, even if it's in a subfolder.

As for standalone build support, I'm going to close this in favour of https://github.com/tailwindlabs/tailwindcss/discussions/6727 since that is more of a feature request than an issue. Again, the extension should work fine without this feature as long as you have a config file in your project. In cases where `tailwindcss` is not installed a bundled version is used instead.

I hope that helps!
