### ISSUE TITLE
False positive cssConflict: transition-colors & transition-opacity

### ISSUE THREAD

**Issue by Angoooose** [tailwindlabs/tailwindcss-intellisense#607]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.7

**What version of Tailwind CSS are you using?**

v3.1.8

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/9ouv211CUQ

**Describe your issue**

I'm getting a `cssConflict` warning for `transition-colors` and `transition-opacity`. However, `transition-colors` doesn't apply any transition to `opacity`. There shouldn't be a conflict.

Warning:

![image](https://user-images.githubusercontent.com/68403129/190546895-5fda3562-7184-4e6f-8b1a-d0e5fc69ddaa.png)

CSS applied from `transition-colors` (importantly it doesn't include `opacity`):

![image](https://user-images.githubusercontent.com/68403129/190547104-a53410a7-2e6f-4ab2-a828-d0f3ef8b2d42.png)

**Comment by bradlc** [comment]
Hey @Angoooose. The classes do conflict because they apply the exact same CSS properties. You can see in your Tailwind Play example that `transition-colors` is completely overridden by `transition-opacity`:

<img width="456" alt="CleanShot 2022-09-16 at 10 02 34@2x" src="https://user-images.githubusercontent.com/2615508/190600342-4346055d-33fd-446f-a06b-3a1cff60e73c.png">

**Comment by Angoooose** [comment]
Oh I see, I misunderstood the warning. Sorry about that, and thanks for your help!
