### ISSUE TITLE
Autocomplete does not work for multiple configs that apply to the same file

### ISSUE THREAD

**Issue by pm0u** [tailwindlabs/tailwindcss-intellisense#665]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

3.2.3

**What package manager are you using?**

yarn v1

**What operating system are you using?**

macOS

**Tailwind config**
```
// main-brand.tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'components/**/*.{js,jsx,ts,tsx}',
    'pages/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    colors: {
      red: '#ff0000'
  },
  plugins: [],
}
```
```
// specific-styles.tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'components/specific-components/**/*.{js,jsx,ts,tsx}',
    'pages/specific-pages/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    colors: {
      red: '#aa00ff'
  },
  plugins: [],
  prefix: 'specific-'
}
```

**VS Code settings**

```
...
  "tailwindCSS.experimental.configFile": {
    "themes/main-brand.tailwind.config.js": ["pages/**/*", "components/**/*"],
    "themes/specific-styles.tailwind.config.js": ["pages/specific-pages/**/*", "components/specific-components/**/*"]
  }
```

**Reproduction URL**

https://github.com/pm0u/tailwindcss-intellisense-multi-config

**Describe your issue**

I would expect autocomplete to provide both `text-red` and `specific-text-red` as an autocomplete option for a file in `pages/specific-pages` but it only provides `text-red`.

**Comment by pm0u** [comment]
Added a repro repository. This seems a little contrived in this particular example since both global stylesheets would end up imported and technically would be available everywhere. But in Next 13 you can import a CSS file anywhere which makes a setup with CSS files/tailwind configs scoped to particular directories more relevant.

**Comment by reinink** [comment]
@pm0u Hey! Thanks for reporting this. Back in October we did [a big update](https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/v0.9.0) to the Intellisense plugin where we improved support for multi-config workspaces, adding support for the new `@config` directive. While working on this we discussed this exact issue — how would we handle situations where a single template is referenced in multiple configs?

Right now, as you know, the Intellisense plugin assumes that each template file matches to a single config file. This is the same way Tailwind works, although you can of course get around this by running multiple builds where you specify which Tailwind config to use for each build process.

To make this work with the Intellisense plugin we'd need to somehow find a way to merge the multiple configs together, but that's difficult to do if there are conflicting values. For example, if both configs define a `color.red.300` value, which value should be used by the Intellisense plugin?

One solution we've tossed around is to provide a config selector in Visual Studio Code, so you can choose which config the Intellisense plugin should use for a particular file, but even that isn't really what you want, since you want both configs to be active at once.

In your particular situation you're using the prefix feature in Tailwind to get around this, so this actually does seem a little more solveable. However, this wasn't exactly the intended purpose of prefixes — rather they are a way to namespace your Tailwind classes so they don't conflict with other CSS libraries or frameworks. Meaning the Intellisense plugin isn't architected in such a way that it understands how to differentiate between multiple configs by looking at the prefix value.

Given that we're just not super clear on how we'd actually like to solve this, we've decided to just keep things simple for now and use the first config found for a particular template file. I could totally see us revisiting this again in the future, especially if we get lots of similar feedback, but I think for now I'm going to close this one, just because it's a bit of a rabbit hole and I think our efforts may be better directed elsewhere at this time 😅

I hope that makes sense Paul! Thanks again for sharing this and for providing it as a well explained issue with an example repo. You'd be amazed at how often we don't get that!
