### ISSUE TITLE
Extension adds all parent directories to watcher (up to root)

### ISSUE THREAD

**Issue by ikapo** [tailwindlabs/tailwindcss-intellisense#701]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.6

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**
npm
**What operating system are you using?**

For example: macOS, Windows

macOS

**Tailwind config**

N/A (no changes to default)

**VS Code settings**

N/A

**Describe your issue**
Whenever the extension starts, I get a `Error: EBADF: bad file descriptor, lstat '/dev/fd/{some number}'`
I have traced this back to `packages/tailwindcss-language-server/src/server.ts:353`.
The while loop causes **all** parent directories to be added, all the way up to / (root).
The variable `temp` there is never assigned, so it runs until the last parent dir.
I wouldn't mind opening a PR to fix this, but what should be the last directory is goes up to? `projectConfig.configPath`?
`git rev-parse --show-toplevel` (current git root)? Maybe uppermost `package.json`?

**Comment by Cosmic-Goat** [comment]
I can confirm this issue, I'm on Linux (using the LSP server in Emacs with [this plugin](https://github.com/merrickluo/lsp-tailwindcss)). At least on Emacs this kills performance and makes the editor quite slow since it adds so many files to the watcher.

According to the [linked issue](https://github.com/microsoft/vscode/issues/60813) from the comment, it seems like the parent folder needs to be added in order to detect file renames? I'm not sure I completely understand, I've only briefly looked over the code.

For fixing the last directory, I would say using [workspace folders](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders) and adding the parent of the uppermost workspace folder to the watcher (perhaps falling back to the parent of [rootUri](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize) if the client doesn't support workspace folders).

Actually looking [here](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/7235aeab48c5cfcf5a142b36ca2c7b91cb1864f8/packages/tailwindcss-language-server/src/server.ts#L1629), it seems that all workspace folders should already be mapped to `projectConfig.folder` - so maybe just adding the parent of that?

**Comment by Cosmic-Goat** [comment]
I've tried just removing the loop altogether and not changing or adding anything else, and it seems to still work fine. Not sure how it will work in VS code though.

**Comment by ikapo** [comment]
@Cosmic-Goat I too am on Emacs with the same plugin.
I agree with you that adding the parent of `projectConfig.folder` should work, I'll try to open a PR soon, will also check it works on VSCode if it isn't too difficult to pack and test the extension.

**Comment by bradlc** [comment]
Hey @ikapo, thanks for reporting this. In the new release (`v0.9.7`) we only watch up to the workspace root 👍 Let me know if you're still having issues
