### ISSUE TITLE
hovering over color box preview shows the css style from preceding class

### ISSUE THREAD

**Issue by nyoungstudios** [tailwindlabs/tailwindcss-intellisense#717]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.7

**What version of Tailwind CSS are you using?**

3.2.7

**What package manager are you using?**

npm

**What operating system are you using?**

Windows in WSL Ubuntu environment

**Tailwind config**

```js
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
}
```

**VS Code settings**

version: 1.75.1

```json
{}
```

**Reproduction URL**

I don't think a repo is necessary, but here are the minimal steps to reproduce the problem:
Initialize project
```bash
mkdir tailwindcss-test
cd tailwindcss-test
npm install -D tailwindcss
code .

# create the tailwind.config.js from above
```

Create a css file, for example `globals.css`
```css
.test {
    @apply mx-2 text-gray-500
}
```

Hover over the class names.

**Describe your issue**

VS Code prepends a box with the color in front of css classes that set the color. However, when you hover over the color box, tailwindcss-intellisense shows the css style from the preceding class rather than the class with the color style. See this video as a demo.

https://user-images.githubusercontent.com/16254116/221447071-524fdfb9-177d-491a-90e4-2042fbf5313d.mp4

**Comment by bradlc** [comment]
Hey @nyoungstudios. This is a VS Code issue which we unfortunately have no control over. When you hover over the color block in your example the position that VS Code sends to the language server (assuming you're using 4 spaces for indentation) is `{ line: 1, character: 15 }`. This position is at the end of the `mx-2` class:

```css
.test {
    @apply mx-2| text-gray-500
}
```

This is why you see the hover information for `mx-2`.

I'm going to close this because it's just how VS Code works and we aren't able to fix it in Tailwind CSS IntelliSense, sorry about that!

**Comment by nyoungstudios** [comment]
Thanks for your quick response. What you said does make sense regarding how the language server works, but do you think it is possible for the space between the two classes to be labeled as the following class rather than the preceding class. I think that would solve this problem as the color box replaces the space in the line. And for classes that don't have a color style, it wouldn't really be much of a change since the space will just be labeled in front rather than following the class name.
