### ISSUE TITLE
Detect tailwind configuration on package.json

### ISSUE THREAD

**Issue by davi-mbatista** [tailwindlabs/tailwindcss-intellisense#82]
It would be nice to trigger the autocompletion if there's a "tailwindcss" entry on `package.json`. Some people like to keep the tooling configuration there to avoid extra files.

When I say entry on the `package.json` I mean something like this:

```
    "postcss": {
        "plugins": {
            "tailwindcss": {}
        }
    },
```
Thanks for the awesome extension though! ❤️

**Comment by mwcarew** [comment]
I'd second this.

**Comment by bradlc** [comment]
Hey @davi-mbatista. Please could you clarify what you mean by this? Are you referring to having the actual Tailwind config itself inside the `package.json` file? Or just a reference to the config?

**Comment by flexchar** [comment]
I assume he means detecting if tailwindcss is listed under dependencies :)

**Comment by davi-mbatista** [comment]
Yeah, that wasn't very clear from my side. I'll update the issue description.

**Comment by bradlc** [comment]
We try to be as responsible as possible with regards to extension activation, which is why we use the `workspaceContains:**/{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js` activation event. In the future we may change the activation event, perhaps to [`onStartupFinished`](https://code.visualstudio.com/api/references/activation-events#onStartupFinished). This would give us a bit more flexibility but for now a config file is required to activate the extension 👍
