### ISSUE TITLE
Color Swatches in the tailwind.config.js Disappearing

### ISSUE THREAD

**Issue by wcrowther** [tailwindlabs/tailwindcss-intellisense#910]
Could be a bug. Could be a feature request. Not sure. 

I am using ver 1.86.2 (user setup) of VsCode
with TailwindCss-Intellisense v.010.05 (and current pre-release) 
on Windows

I would like color swatches in my tailwind.config.js file and can enable them with the Editor: Color Decorations in VsCode.

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/6372711/ad4f0a68-548a-41a3-8ab9-cfcc33c29511)

Below are the swatches as seen in the screenshot below when **TailwindCss-Intellisense** is not enabled. 

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/6372711/55f39ca8-0deb-4e39-a3af-735f6cba345e)

When I enable  **TailwindCss-Intellisense** the swatches disappear. I obviously need the Intellisense more that the color swatches. Is this something that can be fixed with a current setting? Or could it be implemented in a future version so that the native VsCode feature works or the TailwindCss-Intellisense swatches work in the tailwind.config.js file?

Thanks in advance. I love using TailwindCss (never thought I would say that about CSS) and appreciate the team!

**Comment by thecrypticace** [comment]
See https://github.com/tailwindlabs/tailwindcss/discussions/11212

You have the default color decorators enabled in VSCode but those disappear as soon as **any installed extension** provides colors for a given document (even if that list is empty). We only display color swatches for utilities and not _all_ possible color syntax. I think, in this situation, it's best that this is handled at the VSCode level rather than in this extension.

This feature is in their backlog but I'm not sure when/if it'll get implemented unless someone picks it up. I might look into that myself though if I have some time to spare over the next few weeks.
