### ISSUE TITLE
"Unknown at rule @apply" warning in Vue SFC style section

### ISSUE THREAD

**Issue by deisner** [tailwindlabs/tailwindcss-intellisense#991]
**What version of VS Code are you using?**

v1.90.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.12.1

**What version of Tailwind CSS are you using?**

v3.4.4

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**

```json
{}
```

**Reproduction URL**
https://github.com/deisner/tailwind-css-intellisense-atrule-mre

**Describe your issue**

I'm getting an `Unknown at rule @apply css(unknownAtRules)` warning in the style section of my Vue3 SFC:

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/742277/bdca83cd-612b-455f-8a87-79b4a2002562)

Note that the tailwind style is being applied, and intellisense is otherwise working, as you can see with the `text-orange-...` suggestions.

Also, when I commited my chages (or pushed the changes, can't recall), the warning went away. But when I reload the window, it reappears. Maybe there's a race condition?

Thanks for your help!

**Comment by Archetipo95** [comment]
In case you just want to mute the error try with these 2 lines in the vscode settings (global or per project)

```
  "scss.lint.unknownAtRules": "ignore",
  "css.lint.unknownAtRules": "ignore",
```

**Comment by thecrypticace** [comment]
As far as I know there's nothing _we_ can do to address this. This is because Vue SFCs treat `<style>` blocks as the `css` language in VSCode rather than the `tailwindcss` language and afaik there is no setting to change that. You can only do so for certain file extensions — e.g. `.css`.

You _can_ however say `<style scoped lang="postcss">` if the PostCSS plugin is installed in VSCode. Unfortunately this causes problems with syntax highlighting but I'm not certain how to fix that.

So, unfortunately it's not something we can fix ourselves. So perhaps its best to just disable those lint rules for now as @Archetipo95 mentioned above.

**Comment by miguel-arrf** [comment]
For everyone that doesn't want to fully disable css lint, here's a workaround:

1. Create a json file with the following content (I named mine `tailwind.css-data.json`, and put it in the `.vscode` folder at the project root):
```json
{
  "version": 1.1,
  "atDirectives": [
    {
      "name": "@reference",
      "description": "Tailwind directive to import stylesheet for reference without duplicating output CSS.",
      "references": [
        {
          "name": "Tailwind docs",
          "url": "https://tailwindcss.com/docs/functions-and-directives#reference-directive"
        }
      ]
    }
  ]
}
```
2. Update your `settings.json`, to include:
```json
"css.customData": [".vscode/tailwind.css-data.json"]
```
(for those using scss instead of css, use `scss.customData`)
